---
title: "Untitled"
output: html_document
date: "2025-11-04"
---

## Loading packages

```{r load_libraries, warning = FALSE, message = FALSE}
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(stringr)
library(MASS)
library(RColorBrewer)
library(DESeq2)
library(viridis)
library(ggpointdensity)
library(tidyverse)
library(data.table)
library(pheatmap)
library(ComplexHeatmap)
library(UpSetR)
library(readxl)
library(ggsci)
library(ggpointdensity)
library(ggprism)
library(ragg)
theme_set(theme_classic(base_size = 15))

personal_path = "/fh/working/sun_w/sshen/MorPhiC"
path = "/fh/fast/sun_w/MorPhiC/data/MorPhiC_exchange_experiment/"
dat_path = file.path(path, "DRACC-processed/UCSF_exchange_experiment_DRACC_processed_August205/Tables")
```

## Read in meta data

```{r fig.width = 3, fig.height=3}
meta = fread(file.path(personal_path, "UCSF_meta_data.tsv"), data.table = FALSE)
dim(meta)
meta[1:2, ]
names(meta)
names(meta)[apply(meta, 2, \(x) any(is.na(x)))]
library(dplyr)

meta$KO_WT = "WT"
meta$KO_WT[meta$Condition == "full knockdown"] = "KO"
meta$KO_WT[meta$Condition == "degron plus IAA"] = "KO"
meta$KO_WT[meta$Condition == "CRISPRi plus guide plus Dox"] = "KO"

```

## Read in gene count data

```{r}
cts = fread(file.path(dat_path, "genesCounts.csv"), data.table = FALSE)
dim(cts)
# To matrix
cts_dat = data.matrix(cts[, -1])
rownames(cts_dat) = cts$Name
```


### Exclude genes without annotation

```{r}
# Read in gene annotation
gene_anno = fread("/fh/fast/sun_w/sshen/MorPhiC/gencode_v44_primary_assembly_info.tsv")
dim(gene_anno)
cts = cts[cts$Name %in% gene_anno$ensembl_gene_id, ]
cts_dat = cts_dat[rownames(cts_dat) %in% gene_anno$ensembl_gene_id, ]
```

### Discard genes whose expression is 0 in more than 75% of samples

```{r}
gene_info = data.frame(
  apply(cts_dat, 1, min), 
  apply(cts_dat, 1, median), 
  apply(cts_dat, 1, \(x) quantile(x, probs = 0.75)), 
  apply(cts_dat, 1, max)
)
gene_info[1:2, ]
names(gene_info) = c("min", "median", "q75", "max")
summary(gene_info)
table(gene_info$q75 > 0)

# Subset genes
w2kp = which(gene_info$q75 > 0)
cts_dat = cts_dat[w2kp, ]
gene_info = gene_info[w2kp, ]
```

### Check read depth vs. gene expression quantile

```{r, fig.width = 4, fig.height=3}
meta$read_depth = colSums(cts_dat)/1e6
meta$q75 = apply(cts_dat, 2, quantile, probs = 0.75)
my_colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "pink", "green", "blue",
               "#660033", "#A65628", "#F781BF", "#999999", "#66C2A5", "#301934")
names(my_colors) = unique(meta$Dcondition)
```

### DE analysis for UCSF and NW

```{r fig.height=3.2, fig.width=4.8, message=FALSE, warning=FALSE}
model1 = c("NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO", "NW_OSTIR")
sample2kp = which(meta$Dcondition %in% model1)

cts_dat_m = cts_dat[,sample2kp]
meta_m    = meta[sample2kp,]
  
## Generate sample information matrix
sample_info = meta_m
  
# do two steps of filtering
# first, filter based on q75 of each gene
# second, filter based on whether each gene is expressed in at least 75% of the samples

dg_q75 = apply(cts_dat_m, 1, quantile, probs=0.75)
cts_dat_m = cts_dat_m[dg_q75 > 0, ]

print(sprintf("After filtering by gene expression q75, the number of genes reduces from %d to %d", 
              length(dg_q75), nrow(cts_dat_m)))

# update the q75 based on only genes that will be used in the DE analysis
sample_info$q75 = apply(cts_dat_m, 2, quantile, probs = 0.75)
sample_info$log_q75 = log(sample_info$q75)


model1 = c("NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR")
sample2kp = which(meta_m$Dcondition %in% model1)
cts_dat_m_NW = cts_dat_m[,sample2kp]
sample_info_NW = sample_info[sample2kp,]

library(edgeR)
library(limma)

# ---- inputs ----
counts  <- cts_dat_m_NW
colData <- sample_info_NW
rownames(colData) = colnames(counts)
stopifnot(all(colnames(counts) == rownames(colData)))

# ---- group factor: WT vs KO ----
group <- ifelse(colData$KO_WT == "WT",
                "WT", "KO")
group <- factor(group, levels = c("WT","KO"))

design2 <- model.matrix(~ 0 + group)
colnames(design2) <- c("WT","KO")

# ---- normalization + voom (quality weights optional) ----
y2 <- DGEList(counts)
y2 <- calcNormFactors(y2)
v2 <- voom(y2, design2, plot = FALSE)
fitNW <- lmFit(v2, design2)

# ---- KO vs WT contrast ----
L2 <- makeContrasts(KOvsWT = KO - WT, levels = design2)
fitNW <- eBayes(contrasts.fit(fitNW, L2))
ttNWOSTIR   <- topTable(fitNW, coef = "KOvsWT", number = Inf)


model1 = c("NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO", "NW_OSTIR")
sample2kp = which(meta$Dcondition %in% model1)

cts_dat_m = cts_dat[,sample2kp]
meta_m    = meta[sample2kp,]
  
## Generate sample information matrix
sample_info = meta_m
  
# do two steps of filtering
# first, filter based on q75 of each gene
# second, filter based on whether each gene is expressed in at least 75% of the samples

dg_q75 = apply(cts_dat_m, 1, quantile, probs=0.75)
cts_dat_m = cts_dat_m[dg_q75 > 0, ]

print(sprintf("After filtering by gene expression q75, the number of genes reduces from %d to %d", 
              length(dg_q75), nrow(cts_dat_m)))

# update the q75 based on only genes that will be used in the DE analysis
sample_info$q75 = apply(cts_dat_m, 2, quantile, probs = 0.75)
sample_info$log_q75 = log(sample_info$q75)


model1 = c("NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO")
sample2kp = which(meta_m$Dcondition %in% model1)
cts_dat_m_NW = cts_dat_m[,sample2kp]
sample_info_NW = sample_info[sample2kp,]

library(edgeR)
library(limma)

# ---- inputs ----
counts  <- cts_dat_m_NW
colData <- sample_info_NW
rownames(colData) = colnames(counts)
stopifnot(all(colnames(counts) == rownames(colData)))

# ---- group factor: WT vs KO ----
group <- ifelse(colData$KO_WT == "WT",
                "WT", "KO")
group <- factor(group, levels = c("WT","KO"))

design2 <- model.matrix(~ 0 + group)
colnames(design2) <- c("WT","KO")

# ---- normalization + voom (quality weights optional) ----
y2 <- DGEList(counts)
y2 <- calcNormFactors(y2)
v2 <- voom(y2, design2, plot = FALSE)
fitNW <- lmFit(v2, design2)

# ---- KO vs WT contrast ----
L2 <- makeContrasts(KOvsWT = KO - WT, levels = design2)
fitNW <- eBayes(contrasts.fit(fitNW, L2))
ttNWDMSO <- topTable(fitNW, coef = "KOvsWT", number = Inf)

# pheatmap(cor(v2$E))
```

### Volcano plot visualization

```{r}
# Add a significance column for coloring
ttNWOSTIR$threshold <- ttNWOSTIR$adj.P.Val < 0.05 & abs(ttNWOSTIR$logFC) > 1

p1 = ggplot(ttNWOSTIR, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs NW OSTIR",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

ttNWDMSO$threshold <- ttNWDMSO$adj.P.Val < 0.05 & abs(ttNWDMSO$logFC) > 1

p2 = ggplot(ttNWDMSO, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs DMSO for NW",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

width_px  = 2500
height_px = round(width_px * (2/4)) 

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_VolcanoPlot_NW_IAAvsOSTIR.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_VolcanoPlot_NW_IAAvsDMSO.png",sep='')),
  plot     = p2,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)

```

```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)

# 1) add gene symbols and significance flags
ttNWOSTIR2 <- ttNWOSTIR %>%
  mutate(
    gene_name = gene_anno$hgnc_symbol[match(rownames(ttNWOSTIR), gene_anno$ensembl_gene_id)],
    gene_name = ifelse(is.na(gene_name) | gene_name == "", rownames(ttNWOSTIR), gene_name),
    outside   = adj.P.Val < 0.05 & abs(logFC) > 1,
    direction = case_when(
      outside & logFC >  1 ~ "up",
      outside & logFC < -1 ~ "down",
      TRUE                 ~ "ns"
    ),
    neglog10p = -log10(adj.P.Val)
  )

# 2) choose a subset to label (tweak n_label if you want more/less)
n_label <- 25
labels_up   <- ttNWOSTIR2 %>% filter(direction == "up")   %>% arrange(desc(neglog10p)) %>% slice_head(n = n_label)
labels_down <- ttNWOSTIR2 %>% filter(direction == "down") %>% arrange(desc(neglog10p)) %>% slice_head(n = n_label)
labels_df   <- bind_rows(labels_up, labels_down)

# 3) volcano with colored points + outside thresholds + labels
p1 <- ggplot(ttNWOSTIR2, aes(x = logFC, y = neglog10p)) +
  geom_point(aes(color = direction), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("down" = "#2C6FB7", "up" = "#E24A33", "ns" = "grey70")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Volcano Plot: KO IAA vs NW OSTIR",
    x = "log2 Fold Change",
    y = "-log10(adjusted p-value)",
    color = NULL
  ) +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black") +
  geom_text_repel(
    data = labels_df,
    aes(label = gene_name),
    size = 3,
    max.overlaps = Inf,
    box.padding = 0.3,
    point.padding = 0.2,
    min.segment.length = 0,
    segment.alpha = 0.6
  )

# 4) save
ggsave(
  filename = file.path(personal_path, "publication", "UCSF_VolcanoPlot_NW_IAAvsOSTIR.png"),
  plot     = p1,
  device   = ragg::agg_png,
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300
)

```

```{r}
ttNWDMSO = ttNWDMSO[match(rownames(ttNWOSTIR), rownames(ttNWDMSO)), ]
combined_p <- apply(cbind(ttNWDMSO$adj.P.Val, ttNWOSTIR$adj.P.Val), 1, function(x) {
  chisq <- -2 * sum(log(x))
  pchisq(chisq, df = 2 * length(x), lower.tail = FALSE)
})

ttNWDMSO2 = ttNWDMSO
ttNWDMSO2$adj.P.Val = combined_p
ttNWDMSO2$logFC_combined = (ttNWDMSO2$logFC + ttNWOSTIR$logFC) / 2
ttNWDMSO2$threshold <- ttNWDMSO2$adj.P.Val < 0.05 & abs(ttNWDMSO2$logFC_combined) > 1

p1 = ggplot(ttNWDMSO2, aes(x = logFC_combined, y = -log10(adj.P.Val))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs WT combining OSTIR & DMSO",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_VolcanoPlot_NW_IAAvsDMSO_OSTIR.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
ttNWDMSO2 = ttNWDMSO[match(rownames(ttNWOSTIR), rownames(ttNWDMSO)), ]
ttNWDMSO2$adj.P.Val.combined = ttNWOSTIR$adj.P.Val

p1 = ggplot(ttNWDMSO2, aes(-log10(adj.P.Val), -log10(adj.P.Val.combined))) +
    geom_pointdensity() +
    ggtitle(sprintf("Scatter of -log10 adjusted p-values: %s vs %s", "DMSO", "OSTIR")) +
    xlab("DMSO") + ylab("OSTIR") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_pval_NW_DMSOvsOSTIR.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
ttNWDMSO2 = ttNWDMSO[match(rownames(ttNWOSTIR), rownames(ttNWDMSO)), ]
ttNWDMSO2$logFC.combined = ttNWOSTIR$logFC

p1 = ggplot(ttNWDMSO2, aes(logFC, logFC.combined)) +
    geom_pointdensity() +
    ggtitle(sprintf("Scatter of logFC: %s vs %s", "DMSO", "OSTIR")) +
    xlab("DMSO") + ylab("OSTIR") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_logFC_NW_DMSOvsOSTIR.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
ttNWDMSO = ttNWDMSO[match(rownames(ttNWOSTIR), rownames(ttNWDMSO)), ]
combined_p <- apply(cbind(ttNWDMSO$adj.P.Val, ttNWOSTIR$adj.P.Val), 1, function(x) {
  chisq <- -2 * sum(log(x))
  pchisq(chisq, df = 2 * length(x), lower.tail = FALSE)
})

ttNWDMSO2 = ttNWDMSO
ttNWDMSO2$adj.P.Val.combined = combined_p
ttNWDMSO2$adj.P.Val.DMSO = ttNWDMSO2$adj.P.Val
ttNWDMSO2$adj.P.Val.OSTIR = ttNWOSTIR$adj.P.Val

p1 = ggplot(ttNWDMSO2, aes(-log10(adj.P.Val.combined), -log10(adj.P.Val.DMSO))) +
    geom_pointdensity() +
    ggtitle(sprintf("-log10 adjusted p-values: %s vs %s", "Combined", "DMSO")) +
    xlab("Combined") + ylab("DMSO") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

p2 = ggplot(ttNWDMSO2, aes(-log10(adj.P.Val.combined), -log10(adj.P.Val.OSTIR))) +
    geom_pointdensity() +
    ggtitle(sprintf("-log10 adjusted p-values: %s vs %s", "Combined", "OSTIR")) +
    xlab("Combined") + ylab("OSTIR") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_pval_NW_CombinedvsDMSO.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_pval_NW_CombinedvsOSTIR.png",sep='')),
  plot     = p2,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
library(edgeR)
library(limma)

# ---- full set for weight learning ----
model_pool <- c(
  "NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO", "NW_OSTIR",
  "KOLF_Parent_ Plus_Dox", "UCSF_CRISPRi",
  "UCSF_CRISPRi_NKX2_1_guides_No_Dox"
)

keep <- meta$Dcondition %in% model_pool
counts_all <- cts_dat[, keep, drop = FALSE]
info_all   <- meta[keep, , drop = FALSE]

# filter once
dg_q75 <- apply(counts_all, 1, quantile, probs = 0.75)
counts_all <- counts_all[dg_q75 > 0, , drop = FALSE]

# group for weight learning (3 levels: DMSO, IAA, otherWT)
# g_all <- ifelse(info_all$Dcondition == "NW_OSTIR_NKX2_1_Plus_DMSO", "WTt",
#          ifelse(info_all$Dcondition == "NW_OSTIR_NKX2_1_Plus_IAA", "KO", "WTother"))
# g_all <- factor(g_all, levels = c("WTt","KO","WTother"))
g_all = factor(info_all$Dcondition)
design_all <- model.matrix(~ 0 + g_all)

# voom + sample-quality weights on FULL data
y_all <- DGEList(counts_all)
y_all <- calcNormFactors(y_all)
v_all <- voomWithQualityWeights(y_all, design_all, plot = FALSE)  # includes arrayWeights

# ---- subset to the pair (IAA vs DMSO) but KEEP the global weights ----
pair <- info_all$Dcondition %in% c("NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO")

E_sub <- v_all$E[, pair, drop = FALSE]
W_sub <- v_all$weights[, pair, drop = FALSE]
info_sub <- info_all[pair, , drop = FALSE]

group <- factor(ifelse(info_sub$Dcondition == "NW_OSTIR_NKX2_1_Plus_IAA", "KO", "WT"),
                levels = c("WT","KO"))
design <- model.matrix(~ 0 + group); colnames(design) <- c("WT","KO")

fit <- lmFit(E_sub, design, weights = W_sub)
fit <- eBayes(contrasts.fit(fit, cbind(KOvsWT = c(-1, 1))))
tt   <- topTable(fit, coef = "KOvsWT", number = Inf)

tt$threshold <- tt$adj.P.Val < 0.05 & abs(tt$logFC) > 1

p2 = ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs KO DMSO including other WT",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_VolcanoPlot_NW_includingWT.png",sep='')),
  plot     = p2,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```


```{r}
library(DESeq2)

# --- pick samples you want to include in dispersion learning ---
model_pool <- c(
  "NW_OSTIR_NKX2_1_Plus_IAA", "NW_OSTIR_NKX2_1_Plus_DMSO", "NW_OSTIR",
  "KOLF_Parent_ Plus_Dox", "UCSF_CRISPRi",
  "UCSF_CRISPRi_NKX2_1_guides_No_Dox", "KOLF_Parent_Plus_DMSO", "KOLF_Parent"
)
keep <- meta$Dcondition %in% unique(meta$Dcondition)

counts <- cts_dat[, keep, drop = FALSE]
info   <- meta[keep, , drop = FALSE]

# --- group is exactly Dcondition (multi-level); others help dispersion only ---
info$group <- factor(info$Dcondition)

# --- DESeq2 dataset + light filtering ---
dds <- DESeqDataSetFromMatrix(countData = counts, colData = info, design = ~ group)
dds <- dds[rowSums(counts(dds) >= 10) >= 2, ]  # keep genes seen in at least 2 samples

# --- full DESeq pipeline (size factors, dispersion, GLM fit) ---
dds <- DESeq(dds)   # runs estimateSizeFactors + estimateDispersions + nbinomWaldTest

# --- compare ONLY IAA vs DMSO (others are NOT in the contrast) ---
iaa_label  <- "NW_OSTIR_NKX2_1_Plus_IAA"
dmso_label <- "NW_OSTIR_NKX2_1_Plus_DMSO"
res <- results(dds, contrast = c("group", iaa_label, dmso_label))

# (optional) LFC shrinkage for cleaner volcano plots
# If 'ashr' is installed:
# res <- lfcShrink(dds, contrast = c("group", iaa_label, dmso_label), res = res, type = "ashr")

# --- inspect / threshold ---
summary(res)
sig <- subset(res, padj < 0.05 & abs(log2FoldChange) > 1)
summary(res)
res = res[!is.na(res$padj), ]
res[res$padj < 0.05, ]
res$threshold <- res$padj < 0.05 & abs(res$log2FoldChange) > 1


p2 = ggplot(res, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs KO DMSO including all other samples",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "UCSF_VolcanoPlot_NW_includingWT_deseq2.png",sep='')),
  plot     = p2,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
# --- choose which WT sets to compare ---
wt_dms <- c("NW_OSTIR_NKX2_1_Plus_DMSO")
wt_all        <- c("NW_OSTIR_NKX2_1_Plus_DMSO", "NW_OSTIR", "KOLF_Parent_Plus_IAA",
                   "KOLF_Parent_ Plus_Dox", "UCSF_CRISPRi",
                   "UCSF_CRISPRi_NKX2_1_guides_No_Dox",
                   "KOLF_Parent_Plus_DMSO", "KOLF_Parent")

# --- select columns for each set ---
idx_dms <- which(meta$Dcondition %in% wt_dms)
idx_all  <- which(meta$Dcondition %in% wt_all)

dat_dms <- cts_dat[, idx_dms, drop = FALSE]
dat_all  <- cts_dat[, idx_all,  drop = FALSE]

# --- normalize to logCPM so scales are comparable ---
library(edgeR)
y_dms <- cpm(DGEList(dat_dms), log = TRUE, prior.count = 1)
y_all  <- cpm(DGEList(dat_all),  log = TRUE, prior.count = 1)

# --- compute per-gene variance ---
var_dms <- apply(y_dms, 1, var, na.rm = TRUE)
var_all  <- apply(y_all,  1, var, na.rm = TRUE)

# --- compare variance distributions ---
summary(var_dms)
summary(var_all)

# quick visualization
boxplot(list(DMSO_only = var_dms, All_WT = var_all),
        log = "y", ylab = "Per-gene variance (log scale)",
        main = "Variance across WTs")

# how many genes increased / decreased
plot(var_all, var_dms, xlab = "Var of all WT", ylab = "Var of only DMSO")
abline(a = 0, b = 1)
mean(var_all > var_dms)
```
