---
title: "JAX"
output: html_document
date: "2025-11-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages

```{r load_libraries, warning = FALSE, message = FALSE}
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(stringr)
library(MASS)
library(RColorBrewer)
library(DESeq2)
library(viridis)
library(ggpointdensity)
library(tidyverse)
library(data.table)
library(pheatmap)
library(ComplexHeatmap)
library(UpSetR)
library(readxl)
library(ggsci)
library(ggpointdensity)
library(ggprism)
library(ragg)
library(edgeR)
theme_set(theme_classic(base_size = 15))

personal_path = "/fh/working/sun_w/sshen/MorPhiC"
path = "/fh/fast/sun_w/MorPhiC/data/MorPhiC_exchange_experiment/"
dat_path = file.path(path, "DRACC-processed/JAX_exchange_experiment_DRACC_processed_August2025/Tables")
```

## Read in meta data

```{r fig.width = 3, fig.height=3}
meta = fread(file.path(personal_path, "JAX_meta_data.tsv"), data.table = FALSE)
dim(meta)
meta[1:2, ]
names(meta)
names(meta)[apply(meta, 2, \(x) any(is.na(x)))]

table(meta$clonal.label)
table(table(meta$clonal.label))
table(table(meta$label))

meta$timepoint = as.factor(meta$timepoint_value)
meta$model_condition = stringr::str_sub(meta$model_system, start = 1, end = -2)

```

## Read in gene count data

```{r}
cts = fread(file.path(dat_path, "genesCounts.csv"), data.table = FALSE)
dim(cts)
cts[1:2, c(1:2, (ncol(cts) - 1) : ncol(cts))]
# Align counts with meta data
stopifnot(
  setequal(meta$file_id, names(cts)[-1]),
  !any(duplicated(meta$file_id)),
  !any(duplicated(names(cts)[-1]))
)
meta = meta[match(names(cts)[-1], meta$file_id), ]
# To matrix
cts_dat = data.matrix(cts[, -1])
rownames(cts_dat) = cts$Name
```

### Exclude genes without annotation

```{r}
# Read in gene annotation
gene_anno = fread("/fh/fast/sun_w/sshen/MorPhiC/gencode_v44_primary_assembly_info.tsv")
dim(gene_anno)
cts = cts[cts$Name %in% gene_anno$ensembl_gene_id, ]
cts_dat = cts_dat[rownames(cts_dat) %in% gene_anno$ensembl_gene_id, ]
```

### Discard genes whose expression is 0 in more than 75% of samples

```{r}
gene_info = data.frame(
  apply(cts_dat, 1, min), 
  apply(cts_dat, 1, median), 
  apply(cts_dat, 1, \(x) quantile(x, probs = 0.75)), 
  apply(cts_dat, 1, max)
)
gene_info[1:2, ]
names(gene_info) = c("min", "median", "q75", "max")
summary(gene_info)
table(gene_info$q75 > 0)

# Subset genes
w2kp = which(gene_info$q75 > 0)
cts_dat = cts_dat[w2kp, ]
gene_info = gene_info[w2kp, ]
```

### Check read depth vs. gene expression quantile

```{r, fig.width = 4, fig.height=3}
meta$read_depth = colSums(cts_dat)/1e6
meta$q75 = apply(cts_dat, 2, quantile, probs = 0.75)
meta$ko_strategy_clean <- gsub("CTRL_", "", meta$ko_strategy, ignore.case = TRUE)
my_colors <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", 
               "#FFFF33", "#A65628", "#F781BF", "#999999", "#66C2A5", "#301934")
names(my_colors) = unique(meta$ko_strategy_clean)
meta$run_id_short = meta$run_id
```

### PCA for all samples

```{r}
# PCA of all samples
q75 = apply(cts_dat, 1, quantile, probs=0.75)
cts_dat_n = t(cts_dat[q75 > 0,])
cts_dat_n = log(median(meta$q75)*cts_dat_n/meta$q75 + 1)
dim(cts_dat_n)

sample_pca = prcomp(cts_dat_n, center = TRUE, scale. = TRUE)
names(sample_pca)
pc_scores = sample_pca$x
eigen_vals = sample_pca$sdev^2
eigen_vals[1:5]/sum(eigen_vals)
pvs = round(eigen_vals[1:5]/sum(eigen_vals)*100,1)
pvs

PC_df = data.frame(pc_scores)
PC_df = cbind(PC_df, meta)

# Note: if you want the plot to USE the new column, change `color=ko_strategy` 
# to `color=ko_strategy_clean` below. Ensure `my_colors` is updated to match the new names!
gPC = ggplot(PC_df, aes(x = PC1, y = PC2, shape=ko_gene, color=ko_strategy_clean)) +
  geom_point(size=2.5, alpha=0.7) + 
  scale_color_manual(values = my_colors) +
  
  # Replace scale_shape_prism() with explicit manual shapes
  scale_shape_manual(values = c("GCM1" = 10, "WT" = 15)) + 
  
  labs(color="KO type", shape ="KO gene") + 
  xlab(sprintf("PC1 (%.1f%% variance)", pvs[1])) + 
  ylab(sprintf("PC2 (%.1f%% variance)", pvs[2])) + 
  ggtitle("All samples") + 
  guides(
    color = guide_legend(title = NULL, order = 1),
    shape = guide_legend(title = NULL, order = 2)
  ) +
  theme(
    legend.margin = margin(0, 0, 0, 0), 
    legend.box.just = "left", 
    legend.direction = "vertical" 
  )

print(gPC)

width_px  = 1920
height_px = round(width_px * (3/4)) 

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "JAX_PCPlot_all_samples.png",sep='')),
  plot     = gPC,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

### PCA for samples we are using

```{r}
meta$ko_strategy_clean <- gsub("CTRL_", "", meta$ko_strategy, ignore.case = TRUE)
model1 = c("UCSF_Pool1_DMSO_Rep", "UCSF_Pool2_DMSO_Rep", "UCSF_Pool1_DOX_Rep", "UCSF_Pool2_DOX_Rep",
           "NW_C20_DMSO_Rep", "NW_C43_DMSO_Rep", "NW_C20_IAA_Rep", "NW_C43_IAA_Rep",
           "JAX_C01_Rep", "JAX_E04_Rep", "MSK_Clone1_Rep", "MSK_Clone2_Rep", "JAX_MSK_WT", 'NW_Parent_IAA_Rep', 'NW_Parent_DMSO_Rep')
sample2kp = which(meta$model_condition %in% model1)

cts_dat_m = cts_dat[,sample2kp]
meta_m    = meta[sample2kp,]

q75 = apply(cts_dat_m, 1, quantile, probs=0.75)
cts_dat_m_UCSF_NW = t(cts_dat_m[q75 > 0,])
cts_dat_m_UCSF_NW = log(median(meta_m$q75)*cts_dat_m_UCSF_NW/meta_m$q75 + 1)
dim(cts_dat_m_UCSF_NW)
meta_m$clone = stringr::str_split_fixed(meta_m$model_condition, "_", 4)[, 2]
meta_m$clone[meta_m$clone == "MSK"] = "WT"

sample_pca = prcomp(cts_dat_m_UCSF_NW, center = TRUE, scale. = TRUE)
names(sample_pca)
pc_scores = sample_pca$x
eigen_vals = sample_pca$sdev^2
eigen_vals[1:5]/sum(eigen_vals)
pvs = round(eigen_vals[1:5]/sum(eigen_vals)*100,1)
pvs

PC_df = data.frame(pc_scores)
PC_df = cbind(PC_df, meta_m)

gPC = ggplot(PC_df, aes(x = PC1, y = PC2, shape=ko_gene, color=ko_strategy_clean)) +
  geom_point(size=2.5, alpha=0.7) + 
  scale_color_manual(values = my_colors) +
  
  # Replace scale_shape_prism() with explicit manual shapes
  scale_shape_manual(values = c("GCM1" = 10, "WT" = 15)) + 
  
  labs(color="KO type", shape ="KO gene") + 
  xlab(sprintf("PC1 (%.1f%% variance)", pvs[1])) + 
  ylab(sprintf("PC2 (%.1f%% variance)", pvs[2])) + 
  ggtitle("Selected samples") + 
  guides(
    color = guide_legend(title = NULL, order = 1),
    shape = guide_legend(title = NULL, order = 2)
  ) +
  theme(
    legend.margin = margin(0, 0, 0, 0), 
    legend.box.just = "left", 
    legend.direction = "vertical" 
  )

print(gPC)

width_px  = 1920
height_px = round(width_px * (3/4)) 

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "JAX_PCPlot_selected_samples.png",sep='')),
  plot     = gPC,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)

PC_df$model_condition = gsub("_Rep", "", PC_df$model_condition)
gPC = ggplot(PC_df, aes(x = PC1, y = PC2, shape=ko_gene, color=model_condition)) +
  geom_point(size=2.5, alpha=0.7) + 
  # Replace scale_shape_prism() with explicit manual shapes
  scale_shape_manual(values = c("GCM1" = 10, "WT" = 15)) + 
  
  labs(color="KO type", shape ="KO gene") + 
  xlab(sprintf("PC1 (%.1f%% variance)", pvs[1])) + 
  ylab(sprintf("PC2 (%.1f%% variance)", pvs[2])) + 
  ggtitle("Selected samples") + 
  guides(
    color = guide_legend(title = NULL, order = 1),
    shape = guide_legend(title = NULL, order = 2)
  ) +
  theme(
    legend.margin = margin(0, 0, 0, 0), 
    legend.box.just = "left", 
    legend.direction = "vertical" 
  )

print(gPC)

width_px  = 1920
height_px = round(width_px * (3/4)) 

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "JAX_PCPlot_selected_samples_detailed.png",sep='')),
  plot     = gPC,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

### DE analysis for NW

```{r fig.height=3.2, fig.width=4.8, message=FALSE, warning=FALSE}
meta$model_condition = stringr::str_sub(meta$model_system, start = 1, end = -2)

df_size = NULL
model1 = c("UCSF_Pool1_DMSO_Rep", "UCSF_Pool2_DMSO_Rep", "UCSF_Pool1_DOX_Rep", "UCSF_Pool2_DOX_Rep",
           "NW_C20_DMSO_Rep", "NW_C43_DMSO_Rep", "NW_C20_IAA_Rep", "NW_C43_IAA_Rep", "NW_Parent_IAA_Rep", 'NW_Parent_DMSO_Rep')
sample2kp = which(meta$model_condition %in% model1)

cts_dat_m = cts_dat[,sample2kp]
meta_m    = meta[sample2kp,]

table(meta_m$ko_strategy)
stopifnot(all(meta_m$file_id == colnames(cts_dat_m)))
  
## Generate sample information matrix
cols2kp = c("model_condition", "ko_strategy", "ko_gene", 
            "run_id", "run_id_short", "timepoint", "q75")
sample_info = meta_m[,cols2kp]
colnames(sample_info)[which(colnames(sample_info)=="timepoint")] = "day"

dim(sample_info)
sample_info[1:2,]
  
# do two steps of filtering
# first, filter based on q75 of each gene
# second, filter based on whether each gene is expressed in at least 75% of the samples

dg_q75 = apply(cts_dat_m, 1, quantile, probs=0.75)
cts_dat_m = cts_dat_m[dg_q75 > 0, ]

print(sprintf("After filtering by gene expression q75, the number of genes reduces from %d to %d", 
              length(dg_q75), nrow(cts_dat_m)))

# update the q75 based on only genes that will be used in the DE analysis
sample_info$q75 = apply(cts_dat_m, 2, quantile, probs = 0.75)
sample_info$log_q75 = log(sample_info$q75)




model1 = c("NW_C20_DMSO_Rep", "NW_C43_DMSO_Rep", "NW_C20_IAA_Rep", "NW_C43_IAA_Rep")
sample2kp = which(meta_m$model_condition %in% model1)
cts_dat_m_NW = cts_dat_m[,sample2kp]
sample_info_NW = sample_info[sample2kp,]
sample_info_NW$clone = stringr::str_split_fixed(sample_info_NW$model_condition, "_", 4)[, 2]


# ---- inputs ----
counts  <- cts_dat_m_NW
colData <- sample_info_NW
rownames(colData) = colnames(counts)
stopifnot(all(colnames(counts) == rownames(colData)))

# ---- group factor: WT vs KO ----
group <- ifelse(colData$ko_gene == "WT",
                "WT", "KO")
group <- factor(group, levels = c("WT","KO"))

design2 <- model.matrix(~ 0 + group)
colnames(design2) <- c("WT","KO")

# ---- block vector: KO keep clone IDs; WT each unique ----
block <- as.character(colData$clone)
block = paste(block, group, sep = "_")

# ---- normalization + voom (quality weights optional) ----
y2 <- DGEList(counts)
y2 <- calcNormFactors(y2)
v2 <- voom(y2, design2, plot = FALSE)

# ---- estimate correlation & fit ----
corfit2 <- duplicateCorrelation(v2, design2, block = block)
message(sprintf("Estimated intra-clone correlation: %.3f", corfit2$consensus))

fitNW <- lmFit(v2, design2, block = block, correlation = corfit2$consensus)

# ---- KO vs WT contrast ----
L2 <- makeContrasts(KOvsWT = KO - WT, levels = design2)
fitNW1 <- eBayes(contrasts.fit(fitNW, L2))
ttNW1   <- topTable(fitNW1, coef = "KOvsWT", number = Inf)



model1 = c("NW_C20_DMSO_Rep", "NW_C43_DMSO_Rep", "NW_C20_IAA_Rep", "NW_C43_IAA_Rep", 'NW_Parent_IAA_Rep', 'NW_Parent_DMSO_Rep')
sample2kp = which(meta_m$model_condition %in% model1)
cts_dat_m_NW = cts_dat_m[,sample2kp]
sample_info_NW = sample_info[sample2kp,]
sample_info_NW$clone = stringr::str_split_fixed(sample_info_NW$model_condition, "_", 4)[, 2]


# ---- inputs ----
counts  <- cts_dat_m_NW
colData <- sample_info_NW
rownames(colData) = colnames(counts)
stopifnot(all(colnames(counts) == rownames(colData)))

# ---- group factor: WT vs KO ----
group <- ifelse(colData$ko_gene == "WT",
                "WT", "KO")
group <- factor(group, levels = c("WT","KO"))

design2 <- model.matrix(~ 0 + group)
colnames(design2) <- c("WT","KO")

# ---- block vector: KO keep clone IDs; WT each unique ----
block <- as.character(colData$clone)
block = paste(block, group, sep = "_")

# ---- normalization + voom (quality weights optional) ----
y2 <- DGEList(counts)
y2 <- calcNormFactors(y2)
v2 <- voom(y2, design2, plot = FALSE)

# ---- estimate correlation & fit ----
corfit2 <- duplicateCorrelation(v2, design2, block = block)
message(sprintf("Estimated intra-clone correlation: %.3f", corfit2$consensus))

fitNW <- lmFit(v2, design2, block = block, correlation = corfit2$consensus)

# ---- KO vs WT contrast ----
L2 <- makeContrasts(KOvsWT = KO - WT, levels = design2)
fitNW2 <- eBayes(contrasts.fit(fitNW, L2))
ttNW2   <- topTable(fitNW2, coef = "KOvsWT", number = Inf)





model1 = c("NW_C20_IAA_Rep", "NW_C43_IAA_Rep", 'NW_Parent_IAA_Rep', 'NW_Parent_DMSO_Rep')
sample2kp = which(meta_m$model_condition %in% model1)
cts_dat_m_NW = cts_dat_m[,sample2kp]
sample_info_NW = sample_info[sample2kp,]
sample_info_NW$clone = stringr::str_split_fixed(sample_info_NW$model_condition, "_", 4)[, 2]


# ---- inputs ----
counts  <- cts_dat_m_NW
colData <- sample_info_NW
rownames(colData) = colnames(counts)
stopifnot(all(colnames(counts) == rownames(colData)))

# ---- group factor: WT vs KO ----
group <- ifelse(colData$ko_gene == "WT",
                "WT", "KO")
group <- factor(group, levels = c("WT","KO"))

design2 <- model.matrix(~ 0 + group)
colnames(design2) <- c("WT","KO")

# ---- block vector: KO keep clone IDs; WT each unique ----
block <- as.character(colData$clone)
block = paste(block, group, sep = "_")

# ---- normalization + voom (quality weights optional) ----
y2 <- DGEList(counts)
y2 <- calcNormFactors(y2)
v2 <- voom(y2, design2, plot = FALSE)

# ---- estimate correlation & fit ----
corfit2 <- duplicateCorrelation(v2, design2, block = block)
message(sprintf("Estimated intra-clone correlation: %.3f", corfit2$consensus))

fitNW <- lmFit(v2, design2, block = block, correlation = corfit2$consensus)

# ---- KO vs WT contrast ----
L2 <- makeContrasts(KOvsWT = KO - WT, levels = design2)
fitNW3 <- eBayes(contrasts.fit(fitNW, L2))
ttNW3   <- topTable(fitNW3, coef = "KOvsWT", number = Inf)
```

```{r}
ttNW1$threshold <- ttNW1$adj.P.Val < 0.05 & abs(ttNW1$logFC) > 1
ttNW2$threshold <- ttNW2$adj.P.Val < 0.05 & abs(ttNW2$logFC) > 1
ttNW3$threshold <- ttNW3$adj.P.Val < 0.05 & abs(ttNW3$logFC) > 1
ttNW1Sig = ttNW1[ttNW1$threshold, ]
ttNW2Sig = ttNW2[ttNW2$threshold, ]
ttNW3Sig = ttNW2[ttNW3$threshold, ]

print("Number of overlaps between NW with only DMSO and NW with DMSO + parents")
length(intersect(rownames(ttNW1Sig), rownames(ttNW2Sig)))
print("Number of sig. genes for NW with only DMSO")
nrow(ttNW1Sig)
print("Number of sig. genes for NW with DMSO + parents")
nrow(ttNW2Sig)


print("Number of overlaps between NW with only DMSO and NW with parents")
length(intersect(rownames(ttNW1Sig), rownames(ttNW3Sig)))
print("Number of sig. genes for NW with only DMSO")
nrow(ttNW1Sig)
print("Number of sig. genes for NW with parents")
nrow(ttNW3Sig)
```

### Volcano plot visualization

```{r}
# Add a significance column for coloring
ttNW3$threshold <- ttNW3$adj.P.Val < 0.05 & abs(ttNW3$logFC) > 1

p2 = ggplot(ttNW3, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point(aes(color = threshold), alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "red")) +
  theme_minimal(base_size = 14) +
  labs(title = "Volcano Plot: KO IAA vs Parents for NW",
       x = "log2 Fold Change",
       y = "-log10(adjusted p-value)") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "black") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "black")

width_px  = 1920
height_px = round(width_px * (3/4)) 

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "VolcanoPlot_NW_withParents.png",sep='')),
  plot     = p2,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",       
  dpi      = 300,
)
```

```{r}
ttNW1 = ttNW1[match(rownames(ttNW3), rownames(ttNW1)), ]
ttNW1$logFC.parent = ttNW3$logFC

p1 = ggplot(ttNW1, aes(logFC, logFC.parent)) +
    geom_pointdensity() +
    ggtitle(sprintf("Scatter of logFC: %s vs %s", "DMSO", "Parent")) +
    xlab("DMSO") + ylab("Parent") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "JAX_logFC_NW_DMSOvsParent.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```

```{r}
ttNW1 = ttNW1[match(rownames(ttNW3), rownames(ttNW1)), ]
ttNW1$adj.P.Val.parent = ttNW3$adj.P.Val

p1 = ggplot(ttNW1, aes(-log10(adj.P.Val), -log10(adj.P.Val.parent))) +
    geom_pointdensity() +
    ggtitle(sprintf("-log10 adjusted p-values: %s vs %s", "DMSO", "Parent")) +
    xlab("DMSO") + ylab("Parent") +
    theme_classic(base_size = 15) +
    geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed")

ggsave(
  filename = file.path(personal_path, paste0("/publication/", "JAX_pval_NW_DMSOvsParent.png",sep='')),
  plot     = p1,
  device   = ragg::agg_png,     # AGG backend, full alpha support
  bg       = "transparent",
  width    = width_px,
  height   = height_px,
  units    = "px",
  dpi      = 300,
)
```
